[package]
name = "unicode-korean-multitool"
description = "A library providing ways to manipulate modern Korean alphabets"
version = "0.2.1"
authors = ["ylsun <y15un@y15un.dog>"]
license = "MIT"
edition = "2018"
workspace = "../"

[dependencies]
num_enum = { version = "0.5" } # BSD-3-Clause
