[package]
name = "unikorn"
version = "0.1.0"
authors = ["ylsun <y15un@y15un.dog>"]
edition = "2021"
description = "a library for handling korean alphabets in unicode"
license = "MIT"

[dependencies]
num_enum = { version = "0.6" } # MIT
